[tool.semantic_release]
branch="master"
upload="twine upload dist/*"
upload_to_pypi = true
upload_to_repository = true
tag_commit = "true"
changelog_file="CHANGELOG.md"
build_command="python setup.py sdist; python setup.py bdist_wheel"
version_variable = "src/geo_api/configuration.py:__version__"

[tool.semantic_release.remote]
token = "$GH_TOKEN"

[semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true
upload_to_pypi = true
build_command = "python setup.py sdist; python setup.py bdist_wheel"


