[semantic_release]
branch="master"
upload="twine upload dist/*"
upload_to_pypi = "false"
upload_to_repository = "true"
tag_commit = "true"
changelog_file="CHANGELOG.md"
build_command="python setup.py sdist bdist_wheel"

[tool.semantic_release.remote]
token = "token"

[tool.semantic_release]
version_variable = "./src/geo_api/__init__.py:__version__"
